<a href="https://colab.research.google.com/github/PU-WEI-LU/Maching_learning_project/blob/main/Churn_rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing the dataset

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/求職專案資料/Churn_Modelling.csv')

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
#Shape of the dataset (no of rows and no of columns)
dataset.shape


(10000, 14)

In [ ]:
#Displaying the data type of the dataset attributes 
dataset.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
# delete the same data
dataset.drop_duplicates(inplace=True)
dataset.shape

(10000, 14)

In [ ]:
dataset.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
dataset.describe().T

count          mean           std          min  \
RowNumber        10000.0  5.000500e+03   2886.895680         1.00   
CustomerId       10000.0  1.569094e+07  71936.186123  15565701.00   
CreditScore      10000.0  6.505288e+02     96.653299       350.00   
Age              10000.0  3.892180e+01     10.487806        18.00   
Tenure           10000.0  5.012800e+00      2.892174         0.00   
Balance          10000.0  7.648589e+04  62397.405202         0.00   
NumOfProducts    10000.0  1.530200e+00      0.581654         1.00   
HasCrCard        10000.0  7.055000e-01      0.455840         0.00   
IsActiveMember   10000.0  5.151000e-01      0.499797         0.00   
EstimatedSalary  10000.0  1.000902e+05  57510.492818        11.58   
Exited           10000.0  2.037000e-01      0.402769         0.00   

                         25%           50%           75%          max  
RowNumber            2500.75  5.000500e+03  7.500250e+03     10000.00  
CustomerId       15628528.25  1.569074e+07  1.575323e+07  15815690.00  
CreditScore           584.00  6.520000e+02  7.180000e+02       850.00  
Age                    32.00  3.700000e+01  4.400000e+01        92.00  
Tenure                  3.00  5.000000e+00  7.000000e+00        10.00  
Balance                 0.00  9.719854e+04  1.276442e+05    250898.09  
NumOfProducts           1.00  1.000000e+00  2.000000e+00         4.00  
HasCrCard               0.00  1.000000e+00  1.000000e+00         1.00  
IsActiveMember          0.00  1.000000e+00  1.000000e+00         1.00  
EstimatedSalary     51002.11  1.001939e+05  1.493882e+05    199992.48  
Exited                  0.00  0.000000e+00  0.000000e+00         1.00

# Setting X and y

In [ ]:
#X = dataset.iloc[:, 3:13]
#y = dataset.iloc[:, 13]
X = dataset
X = X.drop(["RowNumber","Exited","CustomerId","Surname"],axis=1)
y = dataset["Exited"]


In [ ]:
print(X.head())
print(y.head())

   CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64


# Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder_X_1 = LabelEncoder()
#X["Geography"]= labelencoder_X_1.fit_transform(X["Geography"])

labelencoder_X_2 = LabelEncoder()
X["Gender"] = labelencoder_X_2.fit_transform(X["Gender"])

In [ ]:
print(X["Geography"])

0        France
1         Spain
2        France
3        France
4         Spain
         ...   
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object


In [ ]:
#使用getdummy 不需要labelencoder
X= pd.get_dummies(data = X, columns = ['Geography'] , prefix = 'Geography' , drop_first = True)

In [ ]:
#OneHotEncoder_to_X 如果使用這個將會把pd變成ndarray
#from sklearn.compose import ColumnTransformer
#onehotencoder = ColumnTransformer([("1", OneHotEncoder(), [1])], remainder = 'passthrough')
#remainder = 'passthrough'其他非類變數也要擷取
#X = onehotencoder.fit_transform(X)
#避免虛擬變數陷阱必須刪掉其中一COL
#X = X[:, 1:]

In [ ]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  
0               1        101348.88                  0                0  
1               1        112542.58                  0                1  
2               0        113931.57                  0                0  
3               0         93826.63                  0                0  
4               1         79084.10                  0                1

# Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_Scaler = sc.fit_transform(X_train)
X_test_Scaler = sc.transform(X_test)

#Dimensionality Reduction

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
#pca = PCA(n_components = None)

In [ ]:
#X_train_Scaler = pca.fit_transform(X_train_Scaler)
#X_test_Scaler = pca.transform(X_test_Scaler)
#explained_variance = pca.explained_variance_ratio_
#print(explained_variance)

不適合使用pca ，由於各特徵貢獻類似
測試後發現準確率不會增加



In [ ]:
#pca = PCA(n_components = 9)

In [ ]:
#X_train_Scaler = pca.fit_transform(X_train_Scaler)
#X_test_Scaler = pca.transform(X_test_Scaler)
#explained_variance = pca.explained_variance_ratio_
#print(explained_variance)

#Machine Learning

In [ ]:
from sklearn import metrics

In [ ]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train_Scaler, y_train)
knnpred = knn.predict(X_test_Scaler)
cnf_matrix = metrics.confusion_matrix(y_test, knnpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, knnpred))

[[1547   48]
 [ 268  137]]
Accuracy: 0.842


In [ ]:
#SVC 
from sklearn.svm import SVC
svc= SVC(kernel = 'sigmoid')
svc.fit(X_train_Scaler, np.ravel(y_train,order='C'))
svcpred = svc.predict(X_test_Scaler)
cnf_matrix = metrics.confusion_matrix(y_test, svcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, svcpred))

[[1276  319]
 [ 312   93]]
Accuracy: 0.6845


In [ ]:
#Naive 
from sklearn.naive_bayes import GaussianNB
gaussiannb= GaussianNB()
gaussiannb.fit(X_train_Scaler, np.ravel(y_train,order='C'))
gaussiannbpred = gaussiannb.predict(X_test_Scaler)
cnf_matrix = metrics.confusion_matrix(y_test, gaussiannbpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, gaussiannbpred))

[[1499   96]
 [ 245  160]]
Accuracy: 0.8295


In [ ]:
#Decision Tree
from sklearn import metrics
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(criterion='gini',max_depth=3) #criterion = entopy, gini
dtree.fit(X_train, np.ravel(y_train,order='C'))
dtreepred = dtree.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, dtreepred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, dtreepred))

[[1576   19]
 [ 296  109]]
Accuracy: 0.8425


In [ ]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  
0               1        101348.88                  0                0  
1               1        112542.58                  0                1  
2               0        113931.57                  0                0  
3               0         93826.63                  0                0  
4               1         79084.10                  0                1

解決nd.array columns命名問題>只能用PD命名



In [ ]:
from pydotplus import graph_from_dot_data 
from sklearn.tree import export_graphviz

dtree_data = export_graphviz(dtree, 
  out_file=None,filled=True, rounded=True,
  class_names=['Stay', 'Leave'],
  feature_names=X.columns,
  )
graph = graph_from_dot_data(dtree_data) 
graph.write_png('tree.png')


True

In [ ]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200)#criterion = entopy,gini
rfc.fit(X_train, np.ravel(y_train,order='C'))
rfcpred = rfc.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, rfcpred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, rfcpred))

[[1526   69]
 [ 197  208]]
Accuracy: 0.867


未了解的機器學習算法

In [ ]:
#Ada Boosting
from sklearn.ensemble import AdaBoostClassifier
abcl = AdaBoostClassifier(base_estimator=dtree, n_estimators=60)
abcl=abcl.fit(X_train,np.ravel(y_train,order='C'))
abcl_pred=abcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, abcl_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, abcl_pred))

[[1453  142]
 [ 197  208]]
Accuracy: 0.8305


In [ ]:
#Bagging classfier

from sklearn.ensemble import BaggingClassifier
bgcl = BaggingClassifier(n_estimators=60, max_samples=.7 , oob_score=True)

bgcl.fit(X_train, y_train)
# 預測
test_y_predicted = bgcl.predict(X_test)

# 績效
accuracy = metrics.accuracy_score(y_test, test_y_predicted)
print(accuracy)

0.864


In [ ]:
#Gradient boosting

from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(n_estimators = 50, learning_rate = 0.09, max_depth=5)
gbcl = gbcl.fit(X_train,np.ravel(y_train,order='C'))
test_pred = gbcl.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, test_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, test_pred))

[[1527   68]
 [ 189  216]]
Accuracy: 0.8715


In [ ]:
#XGBooosting
from xgboost import XGBClassifier 
xgb = XGBClassifier()
xgb.fit(X_train, np.ravel(y_train,order='C'))
xgbprd = xgb.predict(X_test)
cnf_matrix = metrics.confusion_matrix(y_test, xgbprd)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, xgbprd))

[[1521   74]
 [ 197  208]]
Accuracy: 0.8645


In [ ]:
from sklearn.metrics import classification_report

print('KNN Reports\n',classification_report(y_test, knnpred))
print('SVC Reports\n',classification_report(y_test, svcpred))
print('Naive BayesReports\n',classification_report(y_test, gaussiannbpred))
print('Decision Tree Reports\n',classification_report(y_test, dtreepred))
print('Ada Boosting\n',classification_report(y_test, abcl_pred))
print('Random Forests Reports\n',classification_report(y_test, rfcpred))
print('Bagging Clasifier',bgcl.oob_score_) 
print('Gradient Boosting',classification_report(y_test, test_pred))
print('XGBoosting\n',classification_report(y_test, xgbprd))

print(y_test)
#以KNN為例
#support : 意思為支持，也就是說真實結果中有多少是該類別。那麼有1595個為0類別，405個為1類別。
#precision：精度=正確預測的個數(TP)/被預測正確的個數(TP+FP)；人話也就是模型預測的結果中有多少是預測正確的
#recall:召回率=正確預測的個數(TP)/預測個數(TP+FN)；人話也就是某個類別測試集中的總量，有多少樣本預測正確了；
#f1-score:F1 = 2*精度*召回率/(精度+召回率)
#macro avg：每個類別評估指標未加權的平均值，比如準確率的 macro avg，(0.85+0.74)/2
#weighted avg：加權平均，就是測試集中樣本量大的，我認爲它更重要，給他設置的權重大點。 準確率:0.85*(1595/2000)+0.74*(405/2000)

KNN Reports
               precision    recall  f1-score   support

           0       0.85      0.97      0.91      1595
           1       0.74      0.34      0.46       405

    accuracy                           0.84      2000
   macro avg       0.80      0.65      0.69      2000
weighted avg       0.83      0.84      0.82      2000

SVC Reports
               precision    recall  f1-score   support

           0       0.80      0.80      0.80      1595
           1       0.23      0.23      0.23       405

    accuracy                           0.68      2000
   macro avg       0.51      0.51      0.51      2000
weighted avg       0.69      0.68      0.69      2000

Naive BayesReports
               precision    recall  f1-score   support

           0       0.86      0.94      0.90      1595
           1       0.62      0.40      0.48       405

    accuracy                           0.83      2000
   macro avg       0.74      0.67      0.69      2000
weighted avg       0.81     

# Applying k-Fold Cross Validatio

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = xgb, X = X, y = y, cv = 10)
print('XGBoosting average accuracies\n',accuracies.mean())
print('XGBoosting standard error\n',accuracies.std())



XGBoosting average accuracies
 0.8635999999999999
XGBoosting standard error
 0.009414881836751864


#Artificial Neural Networks

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Initialising the ANN
classifier = Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
#units=6  x=11 y=1 (11+1)/2=6  >> rule of thumb
#kernel_initializer = 'uniform' 如何初始化權重
#activation = 'relu' 整流線性單位函式（Rectified Linear Unit, ReLU）
#input_dim  number of independent variables

In [ ]:

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [ ]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#如果y有三個以上 units就要改成分類結果個數 ex:3、4、5,activation=softmax

In [ ]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#optimizer = 'adam'  Minimize the loss function
#loss = 'binary_crossentropy' 損失函數 / 3個分類結果以上categorical_crossentropy
#metrics = ['accuracy'] 性能評估器

In [ ]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)
#batch_size 一組數據內包含多少觀察數據
#epochs 多少期的訓練
# Part 3 - Making the predictions and evaluating the model

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.6187 - accuracy: 0.7874
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5287 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5173 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5132 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5080 - accuracy: 0.7960
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5068 - accuracy: 0.7960
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5052 - accuracy: 0.7960
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5049 - accuracy: 0.7960
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.7960
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.5009 - accura

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
#將y_pred變成bool

63/63 [==============================] - 0s 1ms/step


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
# Method 2
from sklearn.metrics import classification_report
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("report:\n",classification_report(y_test,y_pred))


Accuracy: 0.7975
report:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1595
           1       0.00      0.00      0.00       405

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
